### ISSUE TITLE
Does this still working , and it's recomendable to use?

### ISSUE THREAD

**Issue by Klairm** [TricksterGuy/3ds-template#5]
Hey, I justwas able to found this template for 3ds development on code blocks, but does this still work? Or should i keep using the devkitpro Makefile?

**Comment by TricksterGuy** [comment]
Try it you might be surprised... or disappointed

The Makefile provided here may be out of date with whats currently used in devkitpro. If you find any issues using it feel free to put up an issue describing the problem including the error message. And I'll take a look at it when I have time.

Though you should be able to swap out the current DVP Makefile and add all of the targets I added to it, and it'd be a drop in replacement that still works in Code::Blocks.

Though to be fair I hadn't done any new 3ds development in some time.

**Comment by Klairm** [comment]
Sorry for  this kinda off-topic issue, but , I got it working properly,  changed the Makefile only, but if i try to run the with the citra, it apparears this message, which i don't understand at all:

https://imgur.com/a/lZpTgXi

Any suggestion?

**Comment by TricksterGuy** [comment]
You don't use the Run button for any of the targets. They are all set up to execute commands from the Makefile. Hitting the build button should execute the assoociated target from the Makefile.

**Comment by TricksterGuy** [comment]
And if the original Makefile doesn't work anymore, feel free to submit a pull request to update it and I can take a look.

**Comment by Klairm** [comment]
Well the Makefile i'm using does it work, but it's has some edits i made for example for run 3dslink

**Comment by TricksterGuy** [comment]
Update as it turns out I had an older commit lying on my computer here with an update for the Makefile to use citro2d and tex3ds

as far as the makefile I have committed it now works out of the box provided you have devkitpro setup correctly.
