### ISSUE TITLE
I keep getting Makefile error 2 when I keep trying to build files on Code: Blocks

### ISSUE THREAD

**Issue by GoldDa** [TricksterGuy/3ds-template#6]
Hi, I'm really new to Homebrew development.I think I followed the steps to set it up but I feel like I arranged the files wrong or something. Every time I click on "Build" on Code: Blocks, it would give the error "error 2". It doesn't matter if I choose which file I want to build(ex. cia, 3dsx, etc.) Again, I'm not really sure I did the steps correctly as I don't know how to fix this issue. The file explorer image shows my project folder and how it's organized and the makefile one shows the issue itself. I haven't edited anything yet but wanted to build it to test it out. Can you please tell me what I did wrong to fix this issue? If you need more information, please let me know so I can give it to you.

![pass](https://user-images.githubusercontent.com/70769154/94217297-accbf100-feaf-11ea-9165-09c913e833c4.PNG)
![cinema](https://user-images.githubusercontent.com/70769154/94217312-b81f1c80-feaf-11ea-884b-8b3fbd3a35a2.PNG)

**Comment by TricksterGuy** [comment]
Its probably because you named the folder "Test project for 3ds"

Try renaming the folder something like Test_Project_3ds something without spaces.

**Comment by GoldDa** [comment]
> Its probably because you named the folder "Test project for 3ds"
> 
> Try renaming the folder something like Test_Project_3ds something without spaces.

I did but sadly it didn't work. I restarted the process of Code Blocks again and put my project in the first page of my folder. I accidentally deleted one of the PATHs from Windows and now it gives me a new error "no pipe" and gives like 5 different errors. And also keeps opening base_tools.
Is there a way I can fix this issue?
![pass](https://user-images.githubusercontent.com/70769154/94290891-d412d480-ff28-11ea-8a8f-c58f88cec198.PNG)

**Comment by TetrisKid48** [comment]
I'm having the exact same problem. I made a new, blank project and used no spaces but I still get the error. My build log and build messages are the same as the ones posted by GoldDa.

**Comment by TricksterGuy** [comment]
Answer the following.

Which version of Code::Blocks are you using?

Can you copy and paste the full build log from Code::Blocks please?

**Comment by TetrisKid48** [comment]
I'm using version 20.03

here is the full build log: 
```
-------------- Build: 3dsx in devkitpro_cpp_test (compiler: GNU GCC Compiler)---------------

Checking if target is up-to-date: mingw32-make.exe -q -f Makefile 3dsx
Running command: mingw32-make.exe -f Makefile 3dsx
/opt/devkitpro/msys2/usr/bin/sh: line 0: [: too many arguments
mingw32-make.exe[1]: C:/Miscellaneous/3DS: Permission denied
mingw32-make.exe[1]: *** No rule to make target 'Hacking'.  Stop.
mingw32-make.exe: *** [Makefile:161: 3dsx] Error 2
Process terminated with status 2 (0 minute(s), 3 second(s))
1 error(s), 0 warning(s) (0 minute(s), 3 second(s))
```

and here are the build messages:
```
||=== Build: 3dsx in devkitpro_cpp_test (compiler: GNU GCC Compiler) ===|
 [Makefile|161|3dsx] Error 2|
||=== Build failed: 1 error(s), 0 warning(s) (0 minute(s), 3 second(s)) ===|
```

**Comment by TricksterGuy** [comment]
1) in what directory is your code in?
2) Does the code build when executing the Makefile from a command prompt / terminal manually?


I shall repeat my comment from September 24th

> Its probably because you named the folder "Test project for 3ds"
> 
> Try renaming the folder something like Test_Project_3ds something without spaces.

It seems like your directory name is probably "C:/Miscellaneous/3DS Hacking" or something

The devkitpro Makefile used does not work well when put in a directory whose name contains spaces. One could edit the Makefile to get it to work by surrounding directories in quotes, but its much easier to ensure your directory name doesn't contain spaces.

**Comment by TetrisKid48** [comment]
1. i tried renaming the entire path to have no spaces, and i am getting the same error.
2. this is what i get in the command prompt when i use the make command:
```
c:\Miscellaneous\3DS_hacking_resources\homebrew_projects\3ds_cpp_test>make
main.cpp
linking 3ds_cpp_test.elf
make[1]: *** No rule to make target '/c/Miscellaneous/3DS_hacking_resources/homebrew_projects/3ds_cpp_test/resources/icon.png', needed by '/c/Miscellaneous/3DS_hacking_resources/homebrew_projects/3ds_cpp_test/output/3ds_cpp_test.smdh'.  Stop.
make: *** [Makefile:158: all] Error 2
```

**i tried adding an icon.png file to the resources folder, and this has fixed the problem!**
it also works in code::blocks again as well.

**Comment by TricksterGuy** [comment]
Ok good.
