### ISSUE TITLE
Error 2 while compiling to Citra

### ISSUE THREAD

**Issue by keatsoo** [TricksterGuy/3ds-template#7]
Hello,
Ive been trying to compile the "basic" main.cpp file, but i keep getting this error : 
```
Checking if target is up-to-date: mingw32-make.exe -q -f Makefile citra
Running command: mingw32-make.exe -f Makefile citra
process_begin: CreateProcess(NULL, arm-none-eabi-g++ -MMD -MP -MF C:/Users/ajini/Desktop/moh/3DS/My3DSApp1/build/main.d -Wall -O2 -mword-relocations -fomit-frame-pointer -ffunction-sections -march=armv6k -mtune=mpcore -mfloat-abi=hard -mtp=soft -IC:/Users/ajini/Desktop/moh/3DS/My3DSApp1/include -IC:\devkitPro/portlibs/3ds/include -IC:\devkitPro/libctru/include -IC:/Users/ajini/Desktop/moh/3DS/My3DSApp1/build -DARM11 -D_3DS -fno-rtti -fno-exceptions -std=gnu++11 -c C:/Users/ajini/Desktop/moh/3DS/My3DSApp1/source/main.cpp -o main.o, ...) failed.
make (e=2): The specified file hasn't been found.
mingw32-make.exe[1]: *** [C:\devkitPro\devkitARM/base_rules:80: main.o] Error 2
mingw32-make.exe: *** [Makefile:173: citra] Error 2
main.cpp
Process terminated with status 2 (0 minute(s), 3 second(s))
2 error(s), 0 warning(s) (0 minute(s), 3 second(s))
```
I have no idea what this means :/
It also opens base_rules file on code::blocks but there is nothing in it

I tried compiling with cmd and opening citra manually and it worked ??????
Could someone please help ? (i really dont want to have to compile with cmd and open manually citra to test the file 💀)

Thank you in advance

**Comment by TricksterGuy** [comment]
is citra.exe in your PATH?

Does the 3dsx target work? If that builds without error but citra doesn't then the path to citra.exe isn't in your PATH environment variable. 

Echoing README.md

_make [citra](https://github.com/citra-emu/citra) requires having citra installed and in your $PATH_

Seems like you are on Windows so if you don't know how to do this I'd refer you to https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/

**Comment by TricksterGuy** [comment]
Additionally you can just open citra yourself and load the 3dsx file yourself This is what my Makefile does, it builds the 3dsx target and then runs citra for you.

Just switch to the 3dsx target and then open citra if you can't put citra in your PATH.

**Comment by keatsoo** [comment]
> is citra.exe in your PATH?
> 
> 
> 
> Does the 3dsx target work? If that builds without error but citra doesn't then the path to citra.exe isn't in your PATH environment variable. 
> 
> 
> 
> Echoing README.md
> 
> 
> 
> _make [citra](https://github.com/citra-emu/citra) requires having citra installed and in your $PATH_
> 
> 
> 
> Seems like you are on Windows so if you don't know how to do this I'd refer you to https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/
> 
> 

The 3dsx target doesn't work either, and Citra is in my path :/

**Comment by keatsoo** [comment]
Here is the build log when I compile to 3dsx :
```
Checking if target is up-to-date: mingw32-make.exe -q -f Makefile 3dsx
Running command: mingw32-make.exe -f Makefile 3dsx
main.cpp
process_begin: CreateProcess(NULL, arm-none-eabi-g++ -MMD -MP -MF C:/Users/ajini/Desktop/moh/3DS/My3DSApp1/build/main.d -Wall -O2 -mword-relocations -fomit-frame-pointer -ffunction-sections -march=armv6k -mtune=mpcore -mfloat-abi=hard -mtp=soft -IC:/Users/ajini/Desktop/moh/3DS/My3DSApp1/include -IC:\devkitPro/portlibs/3ds/include -IC:\devkitPro/libctru/include -IC:/Users/ajini/Desktop/moh/3DS/My3DSApp1/build -D__3DS__ -fno-rtti -fno-exceptions -std=gnu++11 -c C:/Users/ajini/Desktop/moh/3DS/My3DSApp1/source/main.cpp -o main.o, ...) failed.
make (e=2): The specified file hasn't been found.
mingw32-make.exe[1]: *** [C:\devkitPro\devkitARM/base_rules:80: main.o] Error 2
mingw32-make.exe: *** [Makefile:161: 3dsx] Error 2

```

**Comment by TricksterGuy** [comment]
I vaguely remember this error. Perhaps try switching the compiler from MinGW's make (mingw32-make.exe) to MSYS2's make (make.exe)

**Comment by keatsoo** [comment]
How do I do this ?

**Comment by keatsoo** [comment]
nevermind i figured it out : i just had to add `C:/path_to_devkitpro/msys2/bin` in
`settings>compiler>global compiler settings>toolchain executables> additional paths`
and change the make program in `global compiler settings> program files` from the mingw thing to make.exe and it worked like a charm ! thank you !
