### ISSUE TITLE
"C:\devkitPro\devkitARM\base_rules: recipe for target 'main.o' failed"

### ISSUE THREAD

**Issue by trevorwatkins1129** [TricksterGuy/3ds-template#8]
When the "Build" button is pressed, the following error appears in the console:

"
||=== Build: 3dsx in 3ds (compiler: GNU GCC Compiler) ===|
C:\devkitPro\devkitARM\base_rules|32|recipe for target 'main.o' failed|
Makefile|161|recipe for target '3dsx' failed|
||=== Build failed: 2 error(s), 0 warning(s) (0 minute(s), 2 second(s)) ===|
"

**Comment by TricksterGuy** [comment]
Please post the full output from the 'Build Log' tab.

Aside from one small replacement in the Makefile using the latest devkitpro works out of the box.
